export enum CategoryEnum {
  REFRONT,
  TELL_ME_HOW,
  HOW_TO_GET_A_JOB,
  CLEAN_CODE,
  WHATS_UP,
  A_GOOD_BEGINNING,
  ADVANCED_TOPICS,
  ZERO_TO_HERO,
  THE_TIP_OF_THE_ICEBERG,
  MAKE_IT_BOUNCE,
  TIPS_AND_TRICKS,
  CONCEALED,
}
